### PR TITLE
Stories Tab Mockup and Requirements

### LINKED ISSUE #1: Stories Tab Mockup and Requirements
Acceptance Criteria: 
- [x] Requirements should be clearly written out and ready for implementation
- [x] Sketches should be clear enough to display each requirement

### PR DESCRIPTION
**Pull request by klarmannsonia**
Redo of mockups and requirements for stories tab

### CODE REVIEW

**Review by ahmad-diaa — CHANGES_REQUESTED** [review]
I think we do not need the create story/edit story mockup anymore

**Review by ahmad-diaa — CHANGES_REQUESTED** [review]
Why did you remove `one story` and `grid view` mockups?

**Comment by klarmannsonia** [comment]
> Why did you remove `one story` and `grid view` mockups?

@ahmad-diaa I did not removed them. I changed the content and then the size changed.

**Comment by ahmad-diaa** [comment]
> @ahmad-diaa I did not removed them. I changed the content and then the size changed.

Sorry for that, just figured it out, please ignore this comment.

**Comment by klarmannsonia** [comment]
> I think we do not need the create story/edit story mockup anymore

Should I delete them? And also delete the trash icon, + icon and pen icon? And change the requirements again?

**Comment by ahmad-diaa** [comment]
> Should I delete them? And also delete the trash icon, + icon and pen icon? And change the requirements again?

Yes, that makes sense.

**Review by daliamaarek — APPROVED** [review]

**Review by ahmad-diaa — APPROVED** [review]

**Pull request merged**
